package io.Odyssey.content.minigames.tokkul_pit;

import io.Odyssey.model.entity.player.Player;
import io.Odyssey.util.Misc;

/**
 *
 * @author Jason http://www.rune-server.org/members/jason
 * @date Oct 17, 2013
 */
public class Wave1 {

	public static final int OBSIDIAN_RAPTORL1 = 11363;

	public static final int TOK_XIL1 = 11362;
	public static final int OBSIDIAN_MIDGIT = 11354;
	public static final int OBSIDIAN_RAPTOR = 11353;
	public static final int JADS_OTHER_BUDDY = 11347;
	public static final int JADS_BUDDY = 11346;
	public static final int FOURTH_AGE_JAD = 11345;
	public static int[][] SPAWN_DATA = { { 3352, 4118 }, { 3362, 4117 }, { 3365, 4125 }, { 3367, 4134 }, { 3357, 4133 }, { 3360, 4128 }, { 3352, 4134 } };

	public static int[][] getWaveForType1(Player player) {
		switch(player.fightCavesWaveType1){
			case 1:
				return Wave_1;
			case 2:
				return Wave_2;
			case 3:
				return Wave_3;
			default:
				return Wave_1;
		}
	}

	public static int getHp(int npc) {
		switch (npc) {
			case OBSIDIAN_RAPTORL1:
			case TOK_XIL1:
				return 10;
			case OBSIDIAN_MIDGIT:
				return 20;
			case OBSIDIAN_RAPTOR:
				return 40;
			case JADS_OTHER_BUDDY:
				return 80;
			case JADS_BUDDY:
				return 200;
			case FOURTH_AGE_JAD:
				return 300;
		}
		return 50 + Misc.random(50);
	}

	public static int getMax(int npc) {
		switch (npc) {
			case OBSIDIAN_RAPTORL1:
			case TOK_XIL1:
				return 4;
			case OBSIDIAN_MIDGIT:
				return 7;
			case OBSIDIAN_RAPTOR:
				return 13;
			case JADS_OTHER_BUDDY:
				return 20;
			case JADS_BUDDY:
				return 50;
			case FOURTH_AGE_JAD:
				return 97;
		}
		return 5 + Misc.random(5);
	}

	public static int getAtk(int npc) {
		switch (npc) {
			case OBSIDIAN_RAPTORL1:
			case TOK_XIL1:
				return 30;
			case OBSIDIAN_MIDGIT:
				return 40;
			case OBSIDIAN_RAPTOR:
				return 80;
			case JADS_OTHER_BUDDY:
				return 120;
			case JADS_BUDDY:
				return 150;
			case FOURTH_AGE_JAD:
				return 500;
		}
		return 50 + Misc.random(50);
	}

	public static int getDef(int npc) {
		switch (npc) {
			case OBSIDIAN_RAPTORL1:
			case TOK_XIL1:
				return 20;
			case OBSIDIAN_MIDGIT:
				return 40;
			case OBSIDIAN_RAPTOR:
				return 80;
			case JADS_OTHER_BUDDY:
				return 100;
			case JADS_BUDDY:
				return 120;
			case FOURTH_AGE_JAD:
				return 500;
		}
		return 50 + Misc.random(50);
	}
	public static final int[][] Wave_1 = {
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT, JADS_OTHER_BUDDY },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT, JADS_OTHER_BUDDY },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT, JADS_OTHER_BUDDY, JADS_BUDDY },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT, JADS_OTHER_BUDDY },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, JADS_OTHER_BUDDY },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, JADS_OTHER_BUDDY },
			{ JADS_BUDDY, JADS_BUDDY },
			{ FOURTH_AGE_JAD }
	};

	public static final int[][] Wave_2 = {
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1 },
			{ OBSIDIAN_RAPTOR, TOK_XIL1 },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1 },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1 },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT, JADS_OTHER_BUDDY },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1 },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT, JADS_OTHER_BUDDY },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT, JADS_OTHER_BUDDY },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT, JADS_OTHER_BUDDY, JADS_BUDDY },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT, JADS_BUDDY },
			{ OBSIDIAN_RAPTOR, TOK_XIL1, OBSIDIAN_RAPTORL1, OBSIDIAN_MIDGIT },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, JADS_OTHER_BUDDY }, { JADS_BUDDY, JADS_BUDDY }, { FOURTH_AGE_JAD }
	};

	public static final int[][] Wave_3 = {
			{ OBSIDIAN_RAPTORL1 },
			{ OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ OBSIDIAN_MIDGIT },
			{ OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1 },
			{ OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ OBSIDIAN_MIDGIT, OBSIDIAN_MIDGIT },
			{ OBSIDIAN_RAPTOR },
			{ OBSIDIAN_RAPTOR, OBSIDIAN_RAPTORL1 },
			{ OBSIDIAN_RAPTOR, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT },
			{ OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1 },
			{ OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT, OBSIDIAN_MIDGIT },
			{ OBSIDIAN_RAPTOR, OBSIDIAN_RAPTOR },
			{ JADS_OTHER_BUDDY },
			{ JADS_OTHER_BUDDY, OBSIDIAN_RAPTORL1 },
			{ JADS_OTHER_BUDDY, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ JADS_OTHER_BUDDY, OBSIDIAN_MIDGIT },
			{ JADS_OTHER_BUDDY, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1 },
			{ JADS_OTHER_BUDDY, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ JADS_OTHER_BUDDY, OBSIDIAN_MIDGIT, OBSIDIAN_MIDGIT },
			{ JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR },
			{ JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_RAPTORL1 },
			{ JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT },
			{ JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1 },
			{ JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT, OBSIDIAN_MIDGIT },
			{ JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_RAPTOR },
			{ JADS_OTHER_BUDDY, JADS_OTHER_BUDDY },
			{ JADS_BUDDY },
			{ JADS_BUDDY, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, OBSIDIAN_MIDGIT },
			{ JADS_BUDDY, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, OBSIDIAN_MIDGIT, OBSIDIAN_MIDGIT },
			{ JADS_BUDDY, OBSIDIAN_RAPTOR },
			{ JADS_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT },
			{ JADS_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT, OBSIDIAN_MIDGIT },
			{ JADS_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_RAPTOR },
			{ JADS_BUDDY, JADS_OTHER_BUDDY },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_MIDGIT },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_MIDGIT, OBSIDIAN_MIDGIT },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT, OBSIDIAN_RAPTORL1, OBSIDIAN_RAPTORL1 },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_MIDGIT, OBSIDIAN_MIDGIT },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, OBSIDIAN_RAPTOR, OBSIDIAN_RAPTOR },
			{ JADS_BUDDY, JADS_OTHER_BUDDY, JADS_OTHER_BUDDY },
			{ JADS_BUDDY, JADS_BUDDY },
			{ FOURTH_AGE_JAD }
	};

}
